### ISSUE TITLE
Can we add ability to change background of Flight and Hotel Page ?

### ISSUE THREAD

**Issue by patriksharma** [travelpayouts/travel-app-ios#2]
What I'm expecting is to change the background color to background Image for the App. 

Can we add this capability in SDK ?

**Comment by voidless** [comment]
Currently we have no plans to add support for background images on the search forms.
When there will be more requests for this feature we would add it to the backlog.

Alternatively you can change the color in the ASTJRC.swift file like this:
    override func SEARCH_FORM_BACKGROUND() -> UIColor {
        return UIColor.green
    }
Also you can use patterned image inside the color, but it will not work correctly for full screen images as it will not scale the image but just repeat it until filling the screen
    override func SEARCH_FORM_BACKGROUND() -> UIColor {
        return UIColor(patternImage: UIImage(named: "someImage"))
    }

**Comment by patriksharma** [comment]
Yes I tried pattern image but it stretched out and doesn't look good in it. 
 Color change is fine which is already done but to make UI for attractive We can add some kind of images at the background. Will wait for this feature. Thanks for letting me know

**Comment by f0r3s1** [comment]
> Alternatively you can change the color in the ASTJRC.swift file like this:

But I can't. You restricted this by use Public instead of Open:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/15886508/62567717-7343bb00-b894-11e9-8309-2a1f7cf1812d.png">

And when I tried to override the color I got the message:
<img width="832" alt="image" src="https://user-images.githubusercontent.com/15886508/62567778-953d3d80-b894-11e9-8634-e940cb1d7398.png">
