### ISSUE TITLE
Add tabs?

### ISSUE THREAD

**Issue by riveraj33** [travelpayouts/travel-app-ios#35]
Are we able to add tabs or pages to this app? For example a login, splash screen and/or others? If so, how? Thanks!

**Comment by voidless** [comment]
You can add additional tabs in file ```TravelpayoutsTravelApp/Source/TemplateAppConfiguration.swift```
In the class ```AdditionalTabBarItemsFactory```

**Comment by OurHaystack** [comment]
what code would need to be added below in order to add another tab?

private class AdditionalTabBarItemsFactory: NSObject, AdditionalTabBarItemsFactoryProtocol {
    let infoItem = TabBarViewControllerTabItem(type: .mainViewControllerTabItemTypeCustom,
                                               title: TemplateAppLocalizations.shared.informationTabTitle,
                                               icon: #imageLiteral(resourceName: "info_icon"))

**Comment by OurHaystack** [comment]
func additionalTabItems() -> [JRTabBarViewControllerTabItemProtocol] {
        return [infoItem]
    }

**Comment by tpsupport** [comment]
Hello! 

Apologies for the delayed response.

As of now, you can add only a Car Rental tab. To do this, you need to join one car rental affiliate program from [Travelpayouts programs](https://www.travelpayouts.com/programs). Then you will need to generate an affiliate link and add it to the TravelpayoutsTravelApp/default_config.plist file to parameter car_rental_link. 

**Note**: Don't use Economybookings, because this program can't track a mobile traffic.

You can find more information regarding configurations of Travel app for iOS [here](https://github.com/travelpayouts/travel-app-ios).
