### ISSUE TITLE
I can't build and run the app

### ISSUE THREAD

**Issue by ahmedhlulu** [travelpayouts/travel-app-ios#64]
I can't build and run the app
And when building work, the device heats up significantly and the X-code does not respond
I have a MacBook Air M1

**Comment by ahmedhlulu** [comment]
<img width="1440" alt="Screen Shot 2022-08-15 at 1 03 43 PM" src="https://user-images.githubusercontent.com/100189769/184617219-3769618d-6a2b-4af7-b299-6c33a1d0d575.png">

**Comment by tpsupport** [comment]
Hi! Could you please specify your Xcode version along with the iOS version? Are you trying to build the latest Travel App release — https://github.com/travelpayouts/travel-app-ios/releases/tag/6.6.1?

**Comment by ahmedhlulu** [comment]
I have Xcode 13.4.1

**Comment by tpsupport** [comment]
Could you try running the application using earlier versions of Xcode?

**Comment by Devpheara** [comment]
I have the same issue can't build with SDK. it stack now I try to update Xcode to retry.

**Comment by tpsupport** [comment]
At the moment, our SDK works only with Xcode 13.2.1. 

Unfortunately, we don't have enough human resources for building the project and helping our partners with the issues. The thing is, this project was created a couple of years ago, and it hasn't been developed since then. We only update it regularly so that our partners can use it. At each release, we test the project and provide it to our partners as is to be set up independently on their end.
