### ISSUE TITLE
Error: this SDK is not supported by the compiler

### ISSUE THREAD

**Issue by riveraj33** [travelpayouts/travel-app-ios#65]
Hello. My error is this 

SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.2

Please provide an updated SDK for the current Xcode 13.4.1 swift 5.6.1. Also, iOS 16 and Xcode 14 are right around the corner. Please make this compatible with those on release as the previous year took many months to be compatible with Xcode 13.

**Comment by tpsupport** [comment]
Hello! 

At the moment, our SDK works only with Xcode 13.2.1. 

Unfortunately, we don't have enough human resources for building the project and helping our partners with the issues. The thing is, this project was created a couple of years ago, and it hasn't been developed since then. We only update it regularly so that our partners can use it. At each release, we test the project and provide it to our partners as is to be set up independently on their end.

**Comment by riveraj33** [comment]
Hello. Can you give directions on how we can keep this updated on our own? Soon this won't be compatible with Xcode 14.

**Comment by tpsupport** [comment]
As we mentioned previously, please try to build an app using older version of Xcode (13.2.1).

**Comment by riveraj33** [comment]
Hello. Sure we can build with Xcode 13.2.1. But it seems you will not keep this up to date so we need see how we can keep it up to date for upcoming xcode 14 soon to be released. We are a 1 person dev team and cannot build this from scratch so we need to find a way to keep this updated on our own. Thanks for your understanding b

**Comment by tpsupport** [comment]
We'll try to keep it up to date.

Thank you for your patience.

**Comment by williamadoss79** [comment]
> We'll try to keep it up to date.
> 
> Thank you for your patience.

I suggest that you make the App paid with a monthly or annual subscription, paid by your partners, in order to continue to support the project and update it periodically
