### ISSUE TITLE
Can't run the app after install SDK 

### ISSUE THREAD

**Issue by Devpheara** [travelpayouts/travel-app-ios#66]
Xcode Version 13.4.1, with ios 13
<img width="751" alt="Screen Shot 2022-08-21 at 12 30 37 AM" src="https://user-images.githubusercontent.com/19433980/185759644-515542e0-c4df-4f45-b7bb-84b9aa2af2e7.png">

**Comment by riveraj33** [comment]
Hi did you figure this out? I believe the SDK only works with Xcode 13.2.1. Unfortunately, we cannot use the latest Xcode as this is not updated for it. I'm concerned about Xcode 14 and ios 16 which are right around the corner!

**Comment by tpsupport** [comment]
Hello! 

At the moment, our SDK works only with Xcode 13.2.1. 

Unfortunately, we don't have enough human resources for building the project and helping our partners with the issues. The thing is, this project was created a couple of years ago, and it hasn't been developed since then. We only update it regularly so that our partners can use it. At each release, we test the project and provide it to our partners as is to be set up independently on their end.

**Comment by williamadoss79** [comment]
I suggest that you make the App paid with a monthly or annual subscription, paid by your partners, in order to continue to support the project and update it periodically.

**Comment by tpsupport** [comment]
Thank you for the suggestion! We'll consider it for the future.

**Comment by Devpheara** [comment]
Hello I try on Xcode 13.12.1 now meet error like this what should I do?
<img width="1057" alt="Screen Shot 2022-09-02 at 9 23 20 PM" src="https://user-images.githubusercontent.com/19433980/188170398-26ce08ac-da24-48c2-b318-94902e2780bc.png">

**Comment by Devpheara** [comment]
<img width="1024" alt="Screen Shot 2022-09-02 at 9 34 27 PM" src="https://user-images.githubusercontent.com/19433980/188172481-b30f8fc8-d5d1-43e4-b05f-0472c488d5df.png">

**Comment by tpsupport** [comment]
Hello,
Could you please describe your actions step-by-step? This will help us understand what is causing these errors.

**Comment by Devpheara** [comment]
> 
I just install the SDK with Cocoapod into my project as you said it supports Xcode 13.2.1 I have try with it and show error like the picuture above.
