### ISSUE TITLE
Issue with the localization of the currency

### ISSUE THREAD

**Issue by re1s453** [travelpayouts/travel-app-ios#67]
Currency localization does not work. Can you fix this error please. All apps, that using your source code have this error.  It‘s very important because „USD“ is always displayed as currency, instead of the local currency to match the language. Users currently have to adjust it manually with each installation.![image](https://user-images.githubusercontent.com/101999020/186554003-15044ec1-b9f0-4ad9-8e44-04a9eb0f5478.jpeg)

**Comment by tpsupport** [comment]
Hello! 

Unfortunately, we won't be able to help you with this issue as we don't have enough human resources for building the project and helping our partners with the issues on their end. The thing is, this project was created a couple of years ago, and it hasn't been developed since then. We only update it regularly so that our partners can use it.
